sonar.projectKey=smalaca_legacy-code-task-manager
sonar.organization=smalaca-github
sonar.projectName=Legacy Code - Task Manager
sonar.host.url=https://sonarcloud.io
sonar.links.homepage=https://github.com/smalaca/legacy-code-task-manager
sonar.links.issue=https://github.com/smalaca/legacy-code-task-manager/issues

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

sonar.coverage.jacoco.xmlReportPaths=target/jacoco/jacoco-ut/jacoco.xml
sonar.test.exclusions=**/*Test.java
sonar.java.spotbugs.reportPaths=target/spotbugsXml.xml
sonar.java.pmd.reportPaths=target/pmd.xml
sonar.java.checkstyle.reportPaths=target/checkstyle-result.xml